test: test_token test_type1 test_type2 test_type3 test_type5 test_typeBatched
	go test ./... --count=1

vectors: test
	BATCHED_ISSUANCE_TEST_VECTORS_OUT=batched-issuance-test-vectors.json go test -v -run TestVectorGenerateBatchedIssuance ./...
	ED25519_BLINDING_TEST_VECTORS_OUT=type3-ed25519-blinding-test-vectors.json go test -v -run TestVectorGenerateEd25519Blinding ./...
	ECDSA_BLINDING_TEST_VECTORS_OUT=type3-ecdsa-blinding-test-vectors.json go test -v -run TestVectorGenerateECDSABlinding ./...
	TOKEN_TEST_VECTORS_OUT=token-test-vectors.json go test -v -run TestVectorGenerateToken ./...
	TYPE1_ISSUANCE_TEST_VECTORS_OUT=type1-issuance-test-vectors.json go test -v -run TestVectorGenerateBasicPrivateIssuance ./...
	TYPE5_ISSUANCE_TEST_VECTORS_OUT=type5-issuance-test-vectors.json go test -v -run TestVectorGenerateBatchedPrivateIssuance ./...
	TYPE2_ISSUANCE_TEST_VECTORS_OUT=type2-issuance-test-vectors.json go test -v -run TestVectorGenerateBasicIssuance ./...
	TYPE3_ANON_ORIGIN_ID_TEST_VECTORS_OUT=type3-anon-origin-id-test-vectors.json go test -v -run TestVectorGenerateAnonOriginID ./...
	TYPE3_ORIGIN_ENCRYPTION_TEST_VECTORS_OUT=type3-origin-encryption-test-vectors.json go test -v -run TestVectorGenerateOriginEncryption ./...

bench:
	go test -bench=.

test_token:
	TOKEN_TEST_VECTORS_IN=token-test-vectors.json \
	go test -v --count=1 ./tokens

test_type1:
	TYPE1_ISSUANCE_TEST_VECTORS_IN=type1-issuance-test-vectors.json \
	go test -v --count=1 ./tokens/type1/...

test_type2:
	TYPE2_ISSUANCE_TEST_VECTORS_IN=type2-issuance-test-vectors.json \
	go test -v --count=1 ./tokens/type2/...

test_type3:
	TYPE3_ANON_ORIGIN_ID_TEST_VECTORS_IN=type3-anon-origin-id-test-vectors.json       \
	TYPE3_ORIGIN_ENCRYPTION_TEST_VECTORS_IN=type3-origin-encryption-test-vectors.json \
	ECDSA_BLINDING_TEST_VECTORS_IN=type3-ecdsa-blinding-test-vectors.json             \
	ED25519_BLINDING_TEST_VECTORS_IN=type3-ed25519-blinding-test-vectors.json         \
	go test -v --count=1 ./tokens/type3/...

test_type5:
	TYPE5_ISSUANCE_TEST_VECTORS_IN=type5-issuance-test-vectors.json \
	go test -v --count=1 ./tokens/type5/...

test_typeBatched:
	BATCHED_ISSUANCE_TEST_VECTORS_IN=batched-issuance-test-vectors.json \
	go test -v --count=1 ./tokens/batched/...
	BATCHED_ISSUANCE_TEST_VECTORS_IN=batched-issuance-test-vectors-rust.json \
	go test -v --count=1 ./tokens/batched/...
